### PR TITLE
Added examples and random-color cron script

### PR DESCRIPTION
**Pull request by hvva**
Added more solid-color examples, and created a script to choose a random example and run it. I use this to change the keyboard color every 30 min or so.

Moved modes to the exampleModes folder since some of them do not work for me. Also, blinking, etc, may be too distracting.

### CODE REVIEW

**Comment by stevelacy** [comment]
@hvva Thanks for creating these examples!

Can you update your sh file to run `node` instead of `nodejs`?
`nodejs` is created via the legacy installer, `node` is created when node is built from source, or installed manually.

**Comment by hvva** [comment]
Updated script to run node rather than nodejs.
Also added exampleMode "off.js". The script will check if laptop is on battery. If so, it will turn the keyboard off.

**Comment by stevelacy** [comment]
Will merge with #20

**Comment by timofonic** [comment]
What about making it compatible with the official software? Would it be possible?

if not, what about making the profiles language agnostic? By using some ini-like language that can be used by systemd, the C++ port, desktop managers or applications.

**Comment by stevelacy** [comment]
Closing since no updates from the PR author

**Pull request closed without merging**
